---
title: "DataExploration"
output: html_document
---
Setup:
```{r}
library(ggplot2)
library(png)
library(pheatmap)
library(NbClust)
library(cluster)
library(plyr)
library(dplyr)
library(plotly)
library(ggpubr)
library(factoextra)
source("ASDClusteringParams.R", local= knitr::knit_global())

setwd(params$WorkingDirectory)
load(file = params$FilteredDataFile)
PR <- read.csv(params$ParcellationReferenceFile, sep = ";",stringsAsFactors = F)
```


```{r}
zScore <- function(value, distribution) {
  z <- NA
  if(length(distribution) > params$zScoringMinGroupSize){
    z <- (as.numeric(value) - mean(distribution))/sd(distribution)
  } 
  return(z)
}

zScore_SBJ <- function(s, ftrs, hc) {
  for (f in ftrs) {
    value <- s[f]
    # controlDistribution <- hc[which(round(as.numeric(hc$Age)) == round(as.numeric(s["Age"])) &  hc["site"] == s["site"]),f]
    if (params$zScoringBySite){
      controlDistribution <- hc[which(abs(hc$Age - s["Age"]) < params$zScoringAgeRange &  hc["site"] == s["site"]),f]
      
    } else{
      controlDistribution <- hc[which(abs(hc$Age - s["Age"]) < params$zScoringAgeRange),f]
    }
    s[f] <- zScore(value, controlDistribution)
  }
  return(s)
}

zScore_SBJ_loop <- function(sbj, ftrs, hc) {
  res = list()
  for (i in 1:ncol(sbj)) {
    for (f in ftrs) {
      value <- sbj[i, f]
      # controlDistribution <- hc[which(round(as.numeric(hc$Age)) == round(as.numeric(sbj[i,"Age"])) &  hc[,"site"] == sbj[i,"site"]),f]
      if (params$zScoringBySite){
        controlDistribution <- hc[which((abs(hc$Age - sbj[i,"Age"]) < params$zScoringAgeRange) &  hc[,"site"] == sbj[i,"site"]),f]
      } else {
        controlDistribution <- hc[which((abs(hc$Age - sbj[i,"Age"]) < params$zScoringAgeRange)),f]
      }
      # browser()
      sbj[i,f] <- zScore(value, controlDistribution)
    }
  }
  return(sbj)
}

zScore_leaveOut <- function(s, ftrs, df) {
  for (f in ftrs) {
    # value <- s[f]
    # controlDistribution <- df[which(round(as.numeric(df$Age)) == round(as.numeric(s["Age"])) &  
    #                                   df["site"] == s["site"] &  
    #                                   df["Subject"] == s["Subject"] & 
    #                                   df[params$VID] != s[params$VID]),f]    # value <- s[f]
    if (params$zScoringBySite){
      controlDistribution <- df[which(abs(hc$Age - s["Age"]) < params$zScoringAgeRange  &
                                        df["site"] == s["site"] &
                                        df["Subject"] == s["Subject"] &
                                        df[params$VID] != s[params$VID]),f]
    } else {
      controlDistribution <- df[which(abs(hc$Age - s["Age"]) < params$zScoringAgeRange  &
                                        df["Subject"] == s["Subject"] &
                                        df[params$VID] != s[params$VID]),f]
    }
    
    s[f] <- zScore(value, controlDistribution)
  }
  return(s)
}
zScore_leaveOut_loop <- function(sbj, ftrs, df) {
  res = list()
  for (i in 1:nrow(sbj)) {
    # nControlDistribution = length(df[which(round(as.numeric(df$Age)) == round(as.numeric(sbj[i,"Age"])) &  
    #                                   df[,"site"] == sbj[i,"site"] &  
    #                                   df[,"Subject"] == sbj[i,"Subject"] & 
    #                                   df[,params$VID] != sbj[i,params$VID]),"Age"])
    if (params$zScoringBySite){
      nControlDistribution = length(df[which(round(abs(df$Age - sbj[i,"Age"]) < params$zScoringAgeRange)  &  
                                               df[,"site"] == sbj[i,"site"] &  
                                               df[,"Subject"] == sbj[i,"Subject"] & 
                                               df[,params$VID] != sbj[i,params$VID]),"Age"])
    } else {    
      nControlDistribution = length(df[which(round(abs(df$Age - sbj[i,"Age"]) < params$zScoringAgeRange)  &    
                                               df[,"Subject"] == sbj[i,"Subject"] & 
                                               df[,params$VID] != sbj[i,params$VID]),"Age"]) }
    for (f in ftrs) {
      value <- sbj[i, f]
      # controlDistribution <- df[which(round(as.numeric(df$Age)) == round(as.numeric(sbj[i,"Age"])) &  
      #                               df[,"site"] == sbj[i,"site"] &  
      #                               df[,"Subject"] == sbj[i,"Subject"] & 
      #                               df[,params$VID] != sbj[i,params$VID]),f]
      if (params$zScoringBySite){
        controlDistribution <- df[which(round(abs(df$Age - sbj[i,"Age"]) < params$zScoringAgeRange)  &  
                                          df[,"site"] == sbj[i,"site"] &  
                                          df[,"Subject"] == sbj[i,"Subject"] & 
                                          df[,params$VID] != sbj[i,params$VID]),f]
      } else {  
        controlDistribution <- df[which(round(abs(df$Age - sbj[i,"Age"]) < params$zScoringAgeRange)  &    
                                          df[,"Subject"] == sbj[i,"Subject"] & 
                                          df[,params$VID] != sbj[i,params$VID]),f]
      }
      sbj[i,f] <- zScore(value, controlDistribution)
    }
    
    # sbj[i,]$countZDistribution <- nControlDistribution
  }
  return(sbj)
}

```


```{r}
areas <- append(PR$Area_Left[PR$Area_Left != "" & PR$isParcell == 1], PR$Area_Right[PR$Area_Right != "" & PR$isParcell == 1])
thicknesses <- append(PR$Thickness_Left[PR$Thickness_Left != "" & PR$isParcell == 1], PR$Thickness_Right[PR$Thickness_Right != "" & PR$isParcell == 1])
features <- append(areas,thicknesses)

data[,features] <- lapply(data[,features], as.numeric)
data$Age <- as.numeric(data$Age)

rhm <- data[which(data$Sex == params$Sex & data$EHQ_Total > params$EHQCutoff),]# & data$Protocol == params$Protocols$HCP),]
rhm$site <- factor(rhm$site)

# GLM to extract residuals of [features] ~ Age, Site
formPredictors <- "~ Age * site"
if (params$EHQInResidualCalc) {
  formPredictors <- "~ Age * site * EHQ_Total"
}

for (feature in features) {
  form <- formula(paste(feature,formPredictors)) # change to interaction
  model <- glm(form, data=rhm)
  rhm[,feature] <- model$residuals
}
```

z-scoring of [features] vs HC distribution
```{r}
# zScored <- data
sbj <- rhm[which(rhm$Subject == 1),]# & !is.na(rhm[,features])
hC <- rhm[which(rhm$Subject == 0 & rhm$dxCount <= params$MaxDiagnosisCount),]

asdZScored <-zScore_SBJ_loop(sbj, features, hC)
asdZScored <- asdZScored[complete.cases(asdZScored[,features]),]
hcZScored <- zScore_leaveOut_loop(hC,features,hC)
hcZScored <- hcZScored[complete.cases(hcZScored[,features]),]

```


Clustering
```{r}
featureMatrix <-asdZScored[,features]
asd_distance = dist(featureMatrix, method= params$Distance)
nbResultDB <- NbClust(asdZScored[,features], min.nc = 2, max.nc = 20, method = params$ClusterMethod, index="db")
nbResultDB$Best.nc[1]
params$kList$db = nbResultDB$Best.nc[1]
nbResultSi <- NbClust(asdZScored[,features], min.nc = 2, max.nc = 20, method = params$ClusterMethod, index="silhouette")
nbResultSi$Best.nc[1]
params$kList$silhouette = nbResultSi$Best.nc[1]
# silhouetteResult <- silhouette(2:20, dist = distance)

hcRes = hclust(asd_distance, params$ClusterMethod)
groups = cutree(hcRes, k = params$k())# nbResultDB$Best.nc[1]) #
table(groups)
asdZScored$clust <- groups
```

```{r}
hc_featureMatrix <-hcZScored[,features]
hc_distance = dist(hc_featureMatrix, method=params$Distance)
hc_nbResultDB <- NbClust(hcZScored[,features], min.nc = 2, max.nc = 20, method = params$ClusterMethod, index="db")
hc_nbResultDB$Best.nc[1]
hc_nbResultSi <- NbClust(hcZScored[,features], min.nc = 2, max.nc = 20, method = params$ClusterMethod, index="silhouette")
hc_nbResultSi$Best.nc[1]
# silhouetteResult <- silhouette(2:20, dist = distance)
clusterRes = hclust(hc_distance, params$ClusterMethod)
hc_groups = cutree(clusterRes, k = params$k())# nbResultDB$Best.nc[1]) #
table(hc_groups)
hcZScored$clust <- hc_groups
```

```{r}
descriptives <- list()
for (f in features){
  # zScored[zScored$Subject == 1,f] <- asdZScored[f]
  g <- ggplot(asdZScored, aes(x = asdZScored[,f])) +
  geom_histogram(position = "identity", bins = 8) +
  labs(title=f)
  print(g)
  descriptives <- rbind(descriptives,c(round(mean(asdZScored[,f], na.rm = T),digits = 5), round(sd(asdZScored[,f], na.rm = T),digits = 5), f))
}
for (f in features){
  print(plot(hcZScored[,f]))
}
ggplot(hcZScored, aes(x= seq(1, length(lh.aparc.thickness)),y = rh_transversetemporal_thickness,  color = site)) + geom_point(alpha = 0.2, size = 3) 
ggplot(asdZScored, aes(x= seq(1, length(lh.aparc.thickness)),y = rh_transversetemporal_thickness,  color = site)) + geom_point(alpha = 0.2, size = 3) 
colnames(descriptives) <- c("mean", "standard deviation", "feature")
# kable(
  descriptives
  # )
```


```{r}

for (f in features){
g <- ggplot(asdZScored, aes(y=asdZScored[,f], fill =site)) + 
  geom_boxplot()
print(g)
}
```

```{r}
asdCorrList <- data.frame(parcel = c(), r = c(), p=c())
for (f in features){
  cRes <- cor.test(x = asdZScored[,f], y=asdZScored[,"clust"], method ="spearman", exact=F)
  asdCorrList <- rbind(asdCorrList, data.frame(parcel = f, r = cRes$estimate, p = cRes$p.value))
}
asdCorrList[order(asdCorrList$r),]

hcCorrList <- data.frame(parcel = c(), r = c(), p=c())
for (f in features){
  cRes <- cor.test(x = hcZScored[,f], y=hcZScored[,"clust"], method ="spearman", exact=F)
  hcCorrList <- rbind(hcCorrList, data.frame(parcel = f, r = cRes$estimate, p = cRes$p.value))
}
hcCorrList[order(hcCorrList$r),]

corrDiff <- abs(asdCorrList$r) - abs(hcCorrList$r)
corrDiff[order(corrDiff)]
```

```{r}
pltl <- plot_ly()
factors <- factor(asdZScored$site)
for (i in 1:length(features)){ #
    pltl <- pltl %>% add_markers(x=features[i], y=asdZScored[,features[i]], z= (as.numeric(factors)+(asdZScored$clust-2)*0.1), color= asdZScored$clust,type = "scatter3d", mode="markers")#add_markers(x=features[i], y=asdZScored[,features[i]], z= asdZScored$Site, color= asdZScored$Site,type = "scatter3d", mode="markers")
}
pltl <- pltl %>%
  layout(showlegend = FALSE,
    scene = list(
      xaxis = list(title = "Features"),
      yaxis = list(title = "Values"),
      zaxis = list(title = "Site", 
                   ticktext = levels(factors),
                   tickvals = list(1, 2,3),
                   tickmode = "array")
    ))
pltl
```


```{r}
ggplot(asdZScored, aes(x=site, y=clust))+
  geom_count()
```
```{r}
asdZScored.pca <- prcomp(asdZScored[,features])
fviz_pca_ind(asdZScored.pca, fill.ind = factor(asdZScored$clust), pointshape = 21, pointsize = 2, addEllipses = T, label = "var", axes = c(1,2))
fviz_pca_ind(asdZScored.pca, fill.ind = factor(asdZScored$clust), pointshape = 21, pointsize = 2, addEllipses = T, label = "var", axes = c(3,2))
fviz_pca_ind(asdZScored.pca, fill.ind = factor(asdZScored$clust), pointshape = 21, pointsize = 2, addEllipses = T, label = "var", axes = c(3,4))
fviz_pca_ind(asdZScored.pca, fill.ind = factor(asdZScored$clust), pointshape = 21, pointsize = 2, addEllipses = T, label = "var", axes = c(5,4))
```


```{r}
clustXSite <- chisq.test(asdZScored$clust, asdZScored$site)
clustXProtocol <- chisq.test(asdZScored$clust, asdZScored$Protocol)
siteXProtocol <- chisq.test(asdZScored$site, asdZScored$Protocol)
clustXSite$observed
clustXSite
ggplot(asdZScored, aes(x=clust, y=site))+
  geom_count()
clustXProtocol$observed
clustXProtocol
ggplot(asdZScored, aes(x=clust, y=Protocol))+
  geom_count()
siteXProtocol$observed
siteXProtocol
ggplot(asdZScored, aes(x=site, y=Protocol))+
  geom_count()

ggplot(asdZScored, aes(y= Age, group = clust, fill=clust)) + geom_boxplot()
cor.test(asdZScored$clust, asdZScored$Age)
t_age <- pairwise.t.test(asdZScored$Age, asdZScored$clust, p.adjust.method = "bonferroni")
t_age
```

```{r}
asdZScored$ASSQ_Total <- as.numeric(asdZScored$ASSQ_Total)

cor.test(asdZScored$clust, asdZScored$EHQ_Total)
pairwise.t.test(asdZScored$EHQ_Total, asdZScored$clust, p.adjust.method = "bonferroni")
ggplot(asdZScored, aes(y= EHQ_Total, group = clust, fill=clust)) + geom_boxplot()

cor.test(asdZScored$clust, as.numeric(asdZScored$ASSQ_Total))
pairwise.t.test(asdZScored$ASSQ_Total, asdZScored$clust, p.adjust.method = "bonferroni")
ggplot(asdZScored, aes(y= ASSQ_Total, group = clust, fill=clust)) + geom_boxplot()
cor.test(asdZScored$clust, asdZScored$SRS_Total)
```

```{r}
pairwise.t.test(asdZScored$SRS_Total, asdZScored$clust, p.adjust.method = "bonferroni")
pairwise.t.test(asdZScored$SRS_AWR, asdZScored$clust, p.adjust.method = "bonferroni")
pairwise.t.test(asdZScored$SRS_COG, asdZScored$clust, p.adjust.method = "bonferroni")
pairwise.t.test(asdZScored$SRS_COM, asdZScored$clust, p.adjust.method = "bonferroni")
pairwise.t.test(asdZScored$SRS_DSMRRB, asdZScored$clust, p.adjust.method = "bonferroni")
pairwise.t.test(asdZScored$SRS_MOT, asdZScored$clust, p.adjust.method = "bonferroni")
pairwise.t.test(asdZScored$SRS_SCI, asdZScored$clust, p.adjust.method = "bonferroni")
pairwise.t.test(asdZScored$SRS_RRB, asdZScored$clust, p.adjust.method = "bonferroni")

SRS <- ggplot(asdZScored, aes(y= SRS_Total , group = clust, fill=clust)) + geom_boxplot()
SRS_AWR <- ggplot(asdZScored, aes(y= SRS_AWR , group = clust, fill=clust)) + geom_boxplot()
SRS_COG <- ggplot(asdZScored, aes(y= SRS_COG , group = clust, fill=clust)) + geom_boxplot()
SRS_COM <- ggplot(asdZScored, aes(y= SRS_COM , group = clust, fill=clust)) + geom_boxplot()
SRS_DSMRRB <- ggplot(asdZScored, aes(y= SRS_DSMRRB , group = clust, fill=clust)) + geom_boxplot()
SRS_MOT <- ggplot(asdZScored, aes(y= SRS_MOT , group = clust, fill=clust)) + geom_boxplot()
SRS_SCI <- ggplot(asdZScored, aes(y= SRS_SCI , group = clust, fill=clust)) + geom_boxplot()
SRS_RRB <- ggplot(asdZScored, aes(y= SRS_RRB , group = clust, fill=clust)) + geom_boxplot()
#ggarrange(SRS, ggarrange(SRS_AWR,SRS_COG,SRS_COM,SRS_DSMRRB,SRS_MOT,SRS_SCI,SRS_RRB, ncol=3), nrow=2)
ggarrange(SRS,SRS_AWR,SRS_COG,SRS_COM,SRS_DSMRRB,SRS_MOT,SRS_SCI,SRS_RRB)

for (scale in params$PosthocTestScales) {
  print(
    ggplot(asdZScored, aes(y= asdZScored[,scale], group = clust, fill=clust)) + geom_boxplot() + ylab(scale) + xlab("Cluster"))
  print(
    pairwise.t.test(asdZScored[,scale], asdZScored$clust, p.adjust.method = "bonferroni"))
}

```

```{r}
source("freesurfer_helper.R")
variables <- list()#"ASSQ_Total", "SRS_Total")
# generateFSGDPerSite(asdZScored, data, params$Sites, variables, params$GLMProjectNameASDvHC, directory = params$GLMFolder)
# generateGLMPerSite(sites = params$Sites, features= params$Features, title = params$GLMProjectNameASDvHC, directory = params$GLMFolder)


# generateFSGDASD(asdZScored, variables, params$GLMProjects$ClusteredASD$Title,  directory = params$GLMFolder)
# generateGLMASD(features= params$Features,
#                title = params$GLMProjects$ClusteredASD$Title, 
#                contrasts = params$GLMProjects$ClusteredASD$Contrasts, 
#                directory = params$GLMFolder)

hcNoMissings <- hcZScored
hcNoMissings$clust <- 3
allSubs <- rbind(asdZScored, hcNoMissings[hcNoMissings$Subject == 0,])
generateFSGDALL(allSubs, variables, params$GLMProjects$ClusteredASDvHC$Title, directory = params$GLMFolder)
generateGLMALL(features= params$Features, 
               title = params$GLMProjects$ClusteredASDvHC$Title, 
               contrasts = params$GLMProjects$ClusteredASDvHC$Contrasts, 
               directory = params$GLMFolder)

# hcNoClusters <- allSubs
# hcNoClusters$clust <- hcNoClusters$Subject +1
# generateFSGDASD(hcNoClusters, variables, params$GLMProjects$ASDvHC$Title, directory = params$GLMFolder)
# generateGLMASD(features= params$Features,
#                title = params$GLMProjects$ASDvHC$Title, 
#                contrasts = params$GLMProjects$ASDvHC$Contrasts,
#                directory = params$GLMFolder)

generateSimLinkCMD(asdZScored, hcNoMissings[hcNoMissings$Subject == 0,], params$Sites)

```

```{r}
print_clusters <- function(labels, k) {             
  for(i in 1:k) {
    print(paste("cluster", i))
    print(asdZScored[labels==i,params$VID])
  }
}

```

```{r}

library(fpc)

bootstrapJaccardMeans <- function(sampleDescriptor, featureMatrix, boots){
  distanceMatrix <- dist(featureMatrix, method = params$Distance)
  clusterRes = hclust(distanceMatrix, params$ClusterMethod)
  groups = cutree(clusterRes, k = params$k())
  clustSize <- c(sum(groups == 1), sum(groups==2))
  clustBoot <- clusterboot(distanceMatrix, clustermethod=hclustCBI, method=params$ClusterMethod, k=params$k(), B=boots, multipleboot = T)
  clusterBootJaccardMeans <- data.frame(sample = sampleDescriptor,
                                        c1_Count = clustSize[1], c1_JaccardMean = clustBoot$bootmean[1],
                                        c2_Count = clustSize[2], c2_JaccardMean = clustBoot$bootmean[2])
  return(list(bootResult = clustBoot, jaccardMeans = clusterBootJaccardMeans))
}

JaccardData <- bootstrapJaccardMeans("ASD", asdZScored[,features], boots = params$BootCount)$jaccardMeans
JaccardData <- rbind(JaccardData, bootstrapJaccardMeans("HC", hcZScored[,features], boots = params$BootCount)$jaccardMeans)
JaccardData <- rbind(JaccardData, bootstrapJaccardMeans("HC_ASD", rbind(hcZScored[,features], 
                                                                        asdZScored[,features]), boots=params$BootCount)$jaccardMeans)
JaccardData <- rbind(JaccardData, bootstrapJaccardMeans("HC_ASD1", rbind(hcZScored[,features], 
                                                                        asdZScored[asdZScored$clust==1,features]), boots=params$BootCount)$jaccardMeans)
JaccardData <- rbind(JaccardData, bootstrapJaccardMeans("HC_ASD2", rbind(hcZScored[,features], 
                                                                        asdZScored[asdZScored$clust==2,features]), boots=params$BootCount)$jaccardMeans)
kable(JaccardData)

#diff all, comp asd distr, asd1 hc, asd2 hc
```


```{r}
hcZScored$clust <- 0
allZScored <- rbind.fill(hcZScored, asdZScored)
print(count(allZScored, clust))
ptt <- pairwise.t.test(allZScored[,features], allZScored$clust, p.adjust.method = "bonferroni") 
t.test(allZScored[allZScored$clust == 0,features],allZScored[allZScored$clust == 1,features])
library(rsample)
library(purrr)

resamples <- bootstraps(allZScored, times = 1000)



autoHCClust <- function(dat, features, distanceMethod, clusterMethod, k) {
  featureMatrix <-dat[,features]
  distance = dist(featureMatrix, method = distanceMethod)
  clustRes = hclust(distance, clusterMethod)
  groups = cutree(clustRes, k = k)
  dat$clust <- groups
  return(dat)
}

bootClust <- function(x){
  dat <- as.data.frame(x)
  clustDat <- autoHCClust(dat, features, params$Distance, params$ClusterMethod, params$k())
  formulas <- paste(features, "~ clust")
  output <- t(sapply(formulas, function(form) {
    res <- t.test(as.formula(form), data = clustDat)
    c(res$estimate, statistic = res$statistic, p.value =res$p.value)
  }))
  return(output)
}

bootStrapComp <- map(resamples$splits, bootClust)


tStats <- list()

for (i in 1:length(features)){
  featureTList <- c()
  # tStats[tStats$feature == features[j]]$t <- cbind(tStats[tStats$feature == features[j]]$t, bootStrapComp[[i]][j,3])
  for (j in 1:length(bootStrapComp)) {
    featureTList <- append(featureTList, bootStrapComp[[j]][i,3])
  }
  featureEntry <- list(list(min = min(featureTList),
                       max = max(featureTList),
                       mean = mean(featureTList),
                       sd = sd(featureTList)
                       ))
  names(featureEntry) <- c(features[i])
  tStats <- append(tStats, featureEntry)
}

```

```{r}
demVars <- c("Age", "ASSQ_Total", "SRS_Total")#, "SRS_AWR", "SRS_COG", "SRS_COM", "SRS_DSMRRB", "SRS_MOT", "SRS_SCI", "SRS_RRB")
asd <- asdZScored
asd$group <- 1
hc <- hcZScored[hcZScored$Subject == 0,]
hc$group <- 0
demData <- rbind(asd, hc)
genDemCol <- function(demData, demVars, group, site) {
  print(paste("n =", nrow(demData[demData$group  == group & grepl(site, demData$site),])))
  for (var in demVars) {
    vals <- demData[demData$group  == group & grepl(site, demData$site),var]
    print(paste(var, round(mean(vals, na.rm = T), 2), "+-", round(sd(vals, na.rm = T), 2)))
  }

  return(col)
}
for (i in  c(0,1)) {
    print(paste("site: all","group:",i))
    genDemCol(demData,demVars, i,"*")
}

for (site in unique(demData$site)) {
  for (i in  c(0,1)) {
    print(paste("site: ", site,"group:",i))
    genDemCol(demData, demVars,i,site)
  }
}

for (i in 1:max(asdZScored$clust)){
  print(paste("clust: ", i))
  genDemCol(demData[demData$clust == i,], demVars, 1, "*")
}


```

