---
title: "Andreas MA HBN Preprocessing"
output:
  html_document:
    df_print: paged
---

Setup:
```{r warning=FALSE}
##Packages
library(plyr)
library(dplyr)
library(stringr)
library(knitr)
source("ASDClusteringParams.R", local= knitr::knit_global())
setwd(params$WorkingDirectory)

### Variables
## Behavioral
defaultAllDataCSVPath <- params$AllDataCSV

## MRI
MRIDir <- params$StatsTablesFolder
mriDirPrefix = ""
mriDirSuffix = "/"
```

### Import Behavioral Data:
```{r}
allDataCSV <- params$AllDataCSV #choose.files(default = params$AllDataCSV, multi = F, caption =  "AllData.csv")

allData <- read.csv(allDataCSV)
```

### Import MRI Data
MRI Run ID disasassembler function:
```{r}
## Example input: sub-NDARYZ637LK4_acq-HCP_run-01_T1w
## extracts the HBN subject ID, the scan protocol and the run number
dissassembleRunID <- function(RunID) {
  splt1 <- strsplit(RunID, "_")
  EID <- strsplit(splt1[[1]][1],"-")[[1]][2]
  Protocol <- strsplit(splt1[[1]][2],"-")[[1]][2]
  if (is.na(Protocol)) {
    Protocol = params$Protocols$Other
  }
  Run <- 1
  if (length(splt1[[1]]) == 4) {
    Run <- str_sub(splt1[[1]][3], start = -1)
  }
  
  return(c(EID, Protocol, Run))
}
```

Actual Import:
```{r warning=FALSE}
mriData = data.frame()

## Import Statsfiles 
for (site in params$Sites) {
  lhThickness <- read.csv(paste(MRIDir,mriDirPrefix, site, mriDirSuffix,
                                "aparc_stats_", site, "_thickness_LH.txt",sep=""),sep = "\t", header = TRUE)
  rhThickness <- read.csv(paste(MRIDir,mriDirPrefix, site, mriDirSuffix,
                                "aparc_stats_", site, "_thickness_RH.txt",sep=""),sep = "\t", header = TRUE)
  lhArea <- read.csv(paste(MRIDir,mriDirPrefix, site, mriDirSuffix,
                             "aparc_stats_", site, "_area_LH.txt",sep=""),sep = "\t", header = TRUE)
  rhArea <- read.csv(paste(MRIDir,mriDirPrefix, site, mriDirSuffix,
                             "aparc_stats_", site, "_area_RH.txt",sep=""),sep = "\t", header = TRUE)
  
  siteData <- merge.data.frame(lhThickness, 
                               merge.data.frame(rhThickness, 
                                    merge.data.frame(lhArea, rhArea, by.x = "lh.aparc.area", by.y = "rh.aparc.area", all = TRUE), 
                                    by.x = "rh.aparc.thickness", by.y = "lh.aparc.area", all = TRUE), 
                                    by.x = "lh.aparc.thickness", by.y = "rh.aparc.thickness", all = TRUE)
  
  siteData["site"] <- site
  mriData <- rbind(mriData, siteData)
}

## Clean up resulting variables
mriData <- mriData %>% 
  rename_at(vars(ends_with(".x")), ~str_replace(., "\\..$","")) %>% 
  select_at(vars(-ends_with(".y")))

mriMetaData <- apply(mriData["lh.aparc.thickness"], 1, FUN ="dissassembleRunID")
mriMetaData <- t(mriMetaData)
mriMetaData <- data.frame(EID = mriMetaData[,1],Protocol = mriMetaData[,2],Run = mriMetaData[,3])
mriData["EID"] <- mriMetaData["EID"]
mriData["Run"] <- mriMetaData["Run"]
mriData["Protocol"] <- mriMetaData["Protocol"]
```

### Filtering of MRI Data
```{r}
nTotalMRI <- nrow(mriData)
## only include first runs
mri <- mriData %>% filter(Run == 1) 

## this assembles an table that shows counts at different filtering steps
nRun1 <- nrow(mri)
nHCP <- nrow(filter(mri, Protocol == params$Protocols$HCP))
nVNav <- nrow(filter(mri, Protocol == params$Protocols$VNav))
nVNavN <- nrow(filter(mri, Protocol == params$Protocols$VNavN))
nNA <- nrow(filter(mri, Protocol == params$Protocols$Other))

## Import lists of finished/complete subject states
finishedStates <- read.csv(params$FinishiedStatesFile, col.names = c("Path", "Sub", "State"))
filesComplete <- read.csv(params$CompleteSubjectsFile, col.names = c("Path", "Sub", "State"))
## Exclude subjects with failed imports
incompleteSubjects <- finishedStates[finishedStates$State == 0,]$Sub
incompleteSubjects <- append(incompleteSubjects, filesComplete[filesComplete$State == 0,]$Sub)
mri <- mri %>% filter(!lh.aparc.thickness %in% incompleteSubjects)

## Filter by scan protocol
mri1stChoice <- mri[mri$Protocol == params$Protocols$VNav,]
mri2ndChoice <- mri[mri$Protocol == params$Protocols$VNavN,]
mri3rdChoice <- mri[mri$Protocol == params$Protocols$HCP,]
mri4thChoice <- mri[mri$Protocol == params$Protocols$Other,]

nMultipleScans <- nrow(mri[duplicated(mri$EID),])
mri <- rbind(mri1stChoice, rbind(mri2ndChoice, rbind(mri3rdChoice, mri4thChoice)))
mri$Protocol

## The data is ordered by preference, removing duplicates therefore removes reoccurring IDs with less preferred protocols
mri <- mri %>% filter(!duplicated(EID))

filterCountsMRI <- data.frame(Filter = c("Total T1w", "T1w Run One", "T1w Run, HCP", "T1w Run, VNav",  "T1w Run, VNavNorm", "T1w Run, Not Specified", "Subjects with multiple scans"), countMRI = c(nTotalMRI, nRun1, nHCP, nVNav,nVNavN, nNA, nMultipleScans))
```

### Filtering of Behavioral Data
```{r}
## Filter data to just include autism-diagnosed
nTotalBehavioral <- nrow(allData)
bdAutism <- allData %>% filter(DX_01 == "Autism Spectrum Disorder" | 
                                   DX_02 == "Autism Spectrum Disorder"| 
                                   DX_03 == "Autism Spectrum Disorder"| 
                                   DX_04 == "Autism Spectrum Disorder"| 
                                   DX_05 == "Autism Spectrum Disorder"| 
                                   DX_06 == "Autism Spectrum Disorder"| 
                                   DX_07 == "Autism Spectrum Disorder"| 
                                   DX_08 == "Autism Spectrum Disorder"| 
                                   DX_09 == "Autism Spectrum Disorder"| 
                                   DX_10 == "Autism Spectrum Disorder")
nAutismDiagnosed <- nrow(bdAutism)

## Filter data based on selected sex (males)
bdAutism <- bdAutism %>% filter(Sex == params$Sex)
nMaleASD <- nrow(bdAutism)

## Filter data based on selected handedness cutoff (>= 50)
bdAutism <- bdAutism %>% filter(EHQ_Total >= params$EHQCutoff)
nRhMaleASD <- nrow(bdAutism)
filterCountsBD <- data.frame(Filter = c("Total Behavioral", "Diagnosed with ASD", "Males with ASD", "Right-handed males with ASD"), countBD = c(nTotalBehavioral, nAutismDiagnosed, nMaleASD, nRhMaleASD))
```

### calculate number of diagnosis
```{r}
## loop through all diagnsosis variables and count those that have a specified entry
dx <- c("DX_01", "DX_02", "DX_03", "DX_04", "DX_05", "DX_06", "DX_07", "DX_08", "DX_09", "DX_10")
allData$dxCount <- 0
for (i in 1:nrow(allData)){
  for(d in dx) {
    allData[i,"dxCount"] <- allData[i,"dxCount"] + max(sum(!is.na(allData[i, d]), na.rm =F), 
                                                 sum(allData[i, d] != " ", na.rm =T)) - sum(allData[i, d] == "No Diagnosis Given", na.rm =T) 
  }
}

```


### Import Quatity Data
```{r}
## Import HBN quality data files
qualityDataFiles = c(
  "E:/Box Sync/Arbeit/UZH/MasterArbeit/HBN/QAP/release1_QAP/MRI_qap_anat_RU.csv",
  "E:/Box Sync/Arbeit/UZH/MasterArbeit/HBN/QAP/release1_QAP/MRI_qap_anat_SI.csv",
  "E:/Box Sync/Arbeit/UZH/MasterArbeit/HBN/QAP/release2_QAP/MRI_qap_anat_RU.csv",
  "E:/Box Sync/Arbeit/UZH/MasterArbeit/HBN/QAP/release3_QAP/MRI_qap_anat_CBIC.csv",
  "E:/Box Sync/Arbeit/UZH/MasterArbeit/HBN/QAP/release3_QAP/MRI_qap_anat_RU.csv",
  "E:/Box Sync/Arbeit/UZH/MasterArbeit/HBN/QAP/release4_QAP/MRI_qap_anat_RU.csv",
  "E:/Box Sync/Arbeit/UZH/MasterArbeit/HBN/QAP/release4_QAP/MRI_qap_anat_CBIC.csv",
  "E:/Box Sync/Arbeit/UZH/MasterArbeit/HBN/QAP/release5_QAP/MRI_qap_anat_CBIC.csv",
  "E:/Box Sync/Arbeit/UZH/MasterArbeit/HBN/QAP/release5_QAP/MRI_qap_anat_RU.csv",
  "E:/Box Sync/Arbeit/UZH/MasterArbeit/HBN/QAP/release6_QAP/MRI_qap_anat_CBIC.csv",
  "E:/Box Sync/Arbeit/UZH/MasterArbeit/HBN/QAP/release6_QAP/MRI_qap_anat_RU.csv",
  "E:/Box Sync/Arbeit/UZH/MasterArbeit/HBN/QAP/release7_QAP/MRI_qap_anat_CBIC.csv",
  "E:/Box Sync/Arbeit/UZH/MasterArbeit/HBN/QAP/release7_QAP/MRI_qap_anat_RU.csv"
  )

qualityData <- data.frame()
for (qualityDataFile in qualityDataFiles) {
  qd <- read.csv(qualityDataFile)
  qd <- na.omit(qd)
  qd$external_ID
  qualityData <- rbind(qualityData, qd)
}
## Merge Quality data into the working data set
qualityData$EID <- qualityData$external_ID
qualityData <- subset(qualityData, select = -c(external_ID, Series))
qualityData <- na.omit(qualityData)
qualityData <- qualityData[!duplicated(qualityData[, "EID"]),]
mri <- mri %>% left_join(qualityData, by = "EID")
```


### Joining Behavioral and MRI
```{r}
## First join ASD subjects
subjects <- mri %>% inner_join(bdAutism, by = "EID")
nBDandMRI <- nrow(subjects)
subjects <- subjects %>% filter(ASSQ_Total >= 0 | SRS_Total >= 0)
nOneASDScale <- nrow(subjects)

## Then all other
data <- mri %>% inner_join(allData, by = "EID")
data["Subject"] <- 0
data[data[,"EID"] %in% subjects[,"EID"],]["Subject"] <- 1
data[data$Subject == 0 & data$dxCount > params$MaxDiagnosisCount | (data$EHQ_Total < params$EHQCutoff  | is.na(data$EHQ_Total)),]$Subject <- 2

filterCountsTotal <- data.frame(Filter = c("Total MRI and BD available", "ASD MRI and BD available", " ASD At least one ASD scale"), 
                                countTotal = c(nrow(data),nBDandMRI, nOneASDScale))

save(data, file = params$FilteredDataFile, ascii = T)
```

Data available according to HBN can be seen [here](http://fcon_1000.projects.nitrc.org/indi/cmi_healthy_brain_network/Release%20information.html)

```{r}
filterCounts <- rbind.fill(filterCountsMRI, filterCountsBD)
filterCounts <- rbind.fill(filterCounts, filterCountsTotal)
filterCounts[is.na(filterCounts)] <- "-"
kable(filterCounts)
```

