---
title: "GLMAnalysis"
output: html_document
---

### Setup:
```{r}
library("fsbrain")
library("freesurferformats")
library("stringr")
source("ASDClusteringParams.R", local= knitr::knit_global())
setwd(params$WorkingDirectory)

```

### Functions to load correct files, based on FreeSurfer GLM output:
```{r}
getResultsDirPath <- function(baseDir, hemisphere, projectname, feature, kernelsize, contrastsName) {
  return(
    paste(
      baseDir,
      hemisphere, ".",
      projectname, ".",
      feature, ".",
      kernelsize, ".glmdir/",
      substr(contrastsName,0, nchar(contrastsName) -4), "/",
      sep = ""
    )
  )
}
getGLMResultFiles <- function(dir, threshold, direction) {
  prefix <- paste(dir, "cache.th", as.numeric(threshold)*10,".", direction,".sig.", sep ="")
  return(
    list(
      cluster.summary = paste(prefix, "cluster.summary",sep=""),
      cluster = paste(prefix,"cluster.mgh",sep=""),
      sig = paste(dir, "sig.mgh",sep=""),
      z = paste(dir, "z.mgh",sep=""),
      gamma = paste(dir, "gamma.mgh",sep="")
    )
  )
}
processSummaryFile <- function(summary) {
  fileConn <- file(summary, "r")
  lines <- readLines(fileConn)
  close(fileConn)
  passedHeader = F
  summaryRaw <- c()
  for (line in lines) {
    if (passedHeader) {
      summaryRaw <- append(summaryRaw, line)
    }
    if (startsWith(line, "# ClusterNo")){
      summaryRaw <- c(substr(line, start = 3, stop = 1000))
      passedHeader = T
    }
  }
  summaryCleaned <- c()
  for (line in summaryRaw) {
    summaryCleaned <- append(summaryCleaned, str_replace_all(str_squish(line)," ", ";"))
  }
  summaryDF <- read.table(text = paste(summaryCleaned, collapse = "\n"), sep = ";", header = T, stringsAsFactors = F)
  return(summaryDF)
}
```

### Get files for all specified analyses and generate a table with all significant clusters
```{r}
analysisNames <- c()
glmResultFiles <- list()
glmResultData <- data.frame()
for (project in params$GLMProjects) {
  for (hemi in params$Hemis) {
    for (feature in params$Features) {
      for (contrast in project$Contrasts){
              dir <- getResultsDirPath(baseDir = params$GLMFolder, hemisphere = hemi, 
                               projectname = project$Title, feature =  feature,
                               kernelsize = params$GLMCacheKernel, contrastsName = contrast)
      resFiles <- getGLMResultFiles(dir, params$GLMCacheValue, params$GLMDirections$absolute)
        summary <- processSummaryFile(resFiles$cluster.summary)
        name <- paste(project$Title, hemi, feature, sep =".")
        if (nrow(summary) >= 1){
          summary$analysis <- name
          summary$contrast <-  substr(contrast,0, nchar(contrast) -4)
          summary <- summary[, c(ncol(summary), 2:(ncol(summary)-1))]
          analysisNames <- append(analysisNames, name)
          glmResultData <- rbind(glmResultData, summary)
        }
      
      
      glmResultFiles[[project$Title]][[substr(contrast,0, nchar(contrast) -4)]][[paste(hemi, feature, sep =".")]]<- list (
        files = resFiles
      )
      }
    }
  }
}

```

## Output significant Cluster overview and write the whole table to a file
```{r}
glmOverview <- glmResultData[order(glmResultData$VtxMax,decreasing = T),c("analysis","contrast", "Size.mm.2." , "CWP","Annot")]
glmOverview
write.table(glmResultData, "clipboard",sep="\t",col.names=NA)
write.csv(glmResultData[glmResultData$contrast != "GroupDifferences",], file="../misc/glmResultData.csv", sep=";")
```

```{r}
fsaverage = "E:/Linux/Exchange/fsaverage"

subj_dir = "E:/Linux/Exchange/Site-SI_Derivatives_UZH"

## visualize cluster surfaces
displayMGH <- function(fileCollection,feature, type, analysisName = "_"){
  colFn_diverging  = grDevices::colorRampPalette(RColorBrewer::brewer.pal(11, name="RdBu"));
 
  lh_clust = read.fs.morph (unlist(fileCollection[[paste("lh.",feature, sep="")]]$files[type]), "mgh")
  rh_clust = read.fs.morph (unlist(fileCollection[[paste("rh.",feature, sep="")]]$files[type]), "mgh")
  
  ## If an interactive window is needed, set views=c('si') and don't run lines after
  cm <- vis.data.on.fsaverage(subj_dir, surface = "pial", morph_data_lh = lh_clust, morph_data_rh = rh_clust,bg="aparc", style ="default",  views=c('t4'),draw_colorbar =T, makecmap_options = 
                                list('colFn'=colFn_diverging, 'symm'=TRUE))
  output_brain_img <- paste("../misc/", analysisName,feature, "brain", "png", sep = ".")
  output_cbar_img <- "fsbrain_cbar.png"
  output_final_img <- paste("../misc/", analysisName,feature, "png", sep = ".")

  vislayout.from.coloredmeshes(cm, output_img =output_brain_img)
  coloredmesh.plot.colorbar.separate(cm, image.plot_extra_options = list('horizontal' = TRUE), png_options = list('filename'=output_cbar_img, 'width'=1800))
}

## Differences ASD1 vs ASD2 vs HC
displayMGH(glmResultFiles$ASDComparison$ASD1vsASD2,"thickness", "cluster", analysisName = "ASDComparison_ASD1vASD2")
displayMGH(glmResultFiles$ASDComparison$ASD1vsASD2,"area", "cluster", analysisName = "ASDComparison_ASD1vASD2")

displayMGH(glmResultFiles$ASDComparison$ASD1vsHC,"thickness", "cluster", analysisName = "ASDComparison_ASD1vsHC")
displayMGH(glmResultFiles$ASDComparison$ASD1vsHC,"area", "cluster", analysisName = "ASDComparison_ASD1vsHC")

displayMGH(glmResultFiles$ASDComparison$ASD2vsHC,"thickness", "cluster", analysisName = "ASDComparison_ASD2vsHC")
displayMGH(glmResultFiles$ASDComparison$ASD2vsHC,"area", "cluster", analysisName = "ASDComparison_ASD2vsHC")

## Differences ASD1 vs ASD2 vs HC while including SNR
displayMGH(glmResultFiles$ASDComparisonSNR$ASD1vsASD2COV, "thickness", "cluster", analysisName = "ASDComparisonSNR_ASD1vsHC")
displayMGH(glmResultFiles$ASDComparisonSNR$ASD1vsASD2COV, "area", "cluster", analysisName = "ASDComparisonSNR_ASD1vsHC")

displayMGH(glmResultFiles$ASDComparisonSNR$ASD2vsHCCOV, "thickness", "cluster", analysisName = "ASDComparisonSNR_ASD2vsHCCOV")
displayMGH(glmResultFiles$ASDComparisonSNR$ASD2vsHCCOV, "area", "cluster", analysisName = "ASDComparisonSNR_ASD2vsHCCOV")

displayMGH(glmResultFiles$ASDComparisonSNR$ASD1vsHCCOV, "thickness", "cluster", analysisName = "ASDComparisonSNR_ASD1vsHCCOV")
displayMGH(glmResultFiles$ASDComparisonSNR$ASD1vsHCCOV, "area", "cluster", analysisName = "ASDComparisonSNR_ASD1vsHCCOV")
## Differences ASD vs HC
displayMGH(glmResultFiles$DiagComparison$DiagDifferences, "thickness", "cluster", analysisName = "DiagComparison_DiagDifferences")
displayMGH(glmResultFiles$DiagComparison$DiagDifferences, "area", "cluster", analysisName = "DiagComparison_DiagDifferences")

```