#!/bin/bash
ln -s /home/ubuntu/freesurfer/subjects/fsaverage fsaverage
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARAE012DGA_acq-HCP_T1w sub-NDARAE012DGA_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARAV610EY3_acq-HCP_T1w sub-NDARAV610EY3_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARBK082PDD_acq-HCP_T1w sub-NDARBK082PDD_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARDL511UND_acq-HCP_T1w sub-NDARDL511UND_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDAREM703YFD_acq-HCP_T1w sub-NDAREM703YFD_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDAREX065KJU_acq-HCP_T1w sub-NDAREX065KJU_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARFK610GY5_acq-HCP_T1w sub-NDARFK610GY5_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARGD507TDZ_acq-HCP_T1w sub-NDARGD507TDZ_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARGH790CEF_acq-HCP_T1w sub-NDARGH790CEF_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARGX443CEU_acq-HCP_T1w sub-NDARGX443CEU_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARHB764VZ2_acq-HCP_T1w sub-NDARHB764VZ2_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARJW315BUA_acq-HCP_T1w sub-NDARJW315BUA_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARJW989EM6_acq-HCP_T1w sub-NDARJW989EM6_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARKN509RP9_acq-HCP_T1w sub-NDARKN509RP9_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARKT811ATJ_acq-HCP_T1w sub-NDARKT811ATJ_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARLU111UYF_acq-HCP_T1w sub-NDARLU111UYF_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARLU606ZDD_acq-HCP_T1w sub-NDARLU606ZDD_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARMD575AXD_acq-HCP_T1w sub-NDARMD575AXD_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARMJ333WJM_acq-HCP_T1w sub-NDARMJ333WJM_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARPE056ACA_acq-HCP_T1w sub-NDARPE056ACA_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARPF042DD2_acq-HCP_T1w sub-NDARPF042DD2_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARPX901GZH_acq-HCP_T1w sub-NDARPX901GZH_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARRB338YZ0_acq-HCP_T1w sub-NDARRB338YZ0_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARRK882CLT_acq-HCP_T1w sub-NDARRK882CLT_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARTC527WPZ_acq-HCP_T1w sub-NDARTC527WPZ_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARTF566PYH_acq-HCP_T1w sub-NDARTF566PYH_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARTH473LF8_acq-HCP_T1w sub-NDARTH473LF8_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARTU777GVV_acq-HCP_T1w sub-NDARTU777GVV_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARTZ018PD5_acq-HCP_T1w sub-NDARTZ018PD5_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARUK054GTN_acq-HCP_T1w sub-NDARUK054GTN_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARUK719URM_acq-HCP_T1w sub-NDARUK719URM_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARVG958MHH_acq-HCP_T1w sub-NDARVG958MHH_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARVL555VVA_acq-HCP_T1w sub-NDARVL555VVA_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARVP281CJ4_acq-HCP_T1w sub-NDARVP281CJ4_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARWR628EFJ_acq-HCP_T1w sub-NDARWR628EFJ_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARWV794VM2_acq-HCP_T1w sub-NDARWV794VM2_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARXF203DCD_acq-HCP_T1w sub-NDARXF203DCD_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARXU253JHC_acq-HCP_T1w sub-NDARXU253JHC_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARXV445NYZ_acq-HCP_T1w sub-NDARXV445NYZ_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARYA503XVQ_acq-HCP_T1w sub-NDARYA503XVQ_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARYD546HCB_acq-HCP_T1w sub-NDARYD546HCB_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARYL758JGG_acq-HCP_T1w sub-NDARYL758JGG_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARZD415ZZ1_acq-HCP_T1w sub-NDARZD415ZZ1_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARZG690NHH_acq-HCP_T1w sub-NDARZG690NHH_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARZR529EJ1_acq-HCP_T1w sub-NDARZR529EJ1_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARZV983XK9_acq-HCP_T1w sub-NDARZV983XK9_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARDX196MZP_acq-VNav_run-01_T1w sub-NDARDX196MZP_acq-VNav_run-01_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARDY741VEB_acq-VNav_run-01_T1w sub-NDARDY741VEB_acq-VNav_run-01_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARAD232HVV_acq-HCP_T1w sub-NDARAD232HVV_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARAE358VBE_acq-HCP_T1w sub-NDARAE358VBE_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARAH503YG1_acq-HCP_T1w sub-NDARAH503YG1_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARAM848GTE_acq-HCP_T1w sub-NDARAM848GTE_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARAP785CTE_acq-HCP_T1w sub-NDARAP785CTE_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARAX272ZJL_acq-HCP_T1w sub-NDARAX272ZJL_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARAX358NB5_acq-HCP_T1w sub-NDARAX358NB5_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARBW525JHY_acq-HCP_T1w sub-NDARBW525JHY_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARCA740UC8_acq-HCP_T1w sub-NDARCA740UC8_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARCG037CX4_acq-HCP_T1w sub-NDARCG037CX4_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARCV944JA6_acq-HCP_T1w sub-NDARCV944JA6_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARDR236FWH_acq-HCP_T1w sub-NDARDR236FWH_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARDW711NYZ_acq-HCP_T1w sub-NDARDW711NYZ_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDAREM609ZXW_acq-HCP_T1w sub-NDAREM609ZXW_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDAREY778CR9_acq-HCP_T1w sub-NDAREY778CR9_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARFA860RPD_acq-HCP_T1w sub-NDARFA860RPD_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARFW578RU9_acq-HCP_T1w sub-NDARFW578RU9_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARFX710UZA_acq-HCP_T1w sub-NDARFX710UZA_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARGG539YGN_acq-HCP_T1w sub-NDARGG539YGN_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARGK672URV_acq-HCP_T1w sub-NDARGK672URV_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARGR354WBH_acq-HCP_T1w sub-NDARGR354WBH_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARGT267UZR_acq-HCP_T1w sub-NDARGT267UZR_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARGU485JJA_acq-HCP_T1w sub-NDARGU485JJA_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARHC661KGK_acq-HCP_T1w sub-NDARHC661KGK_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARHX418ZGJ_acq-HCP_T1w sub-NDARHX418ZGJ_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARJY033DKZ_acq-HCP_T1w sub-NDARJY033DKZ_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARKH171DG8_acq-HCP_T1w sub-NDARKH171DG8_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARKP053GCC_acq-HCP_T1w sub-NDARKP053GCC_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARLD287MLP_acq-HCP_T1w sub-NDARLD287MLP_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARLD738DUM_acq-HCP_T1w sub-NDARLD738DUM_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARLJ654TZ0_acq-HCP_T1w sub-NDARLJ654TZ0_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARLM877UZM_acq-HCP_T1w sub-NDARLM877UZM_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARLR039GJL_acq-HCP_T1w sub-NDARLR039GJL_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARLY585ZVN_acq-HCP_T1w sub-NDARLY585ZVN_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARMJ495DE0_acq-HCP_T1w sub-NDARMJ495DE0_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARML406ZB8_acq-HCP_T1w sub-NDARML406ZB8_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARMM951YEH_acq-HCP_T1w sub-NDARMM951YEH_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARMY294VNE_acq-HCP_T1w sub-NDARMY294VNE_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARNF341BNN_acq-HCP_T1w sub-NDARNF341BNN_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARPP622WV4_acq-HCP_T1w sub-NDARPP622WV4_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARRA933RLX_acq-HCP_T1w sub-NDARRA933RLX_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARRC016UZE_acq-HCP_T1w sub-NDARRC016UZE_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARRM158VXD_acq-HCP_T1w sub-NDARRM158VXD_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARRP008LJ6_acq-HCP_T1w sub-NDARRP008LJ6_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARRZ927VC3_acq-HCP_T1w sub-NDARRZ927VC3_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARTP313AGH_acq-HCP_T1w sub-NDARTP313AGH_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARUC144FN6_acq-HCP_T1w sub-NDARUC144FN6_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARUC715YN4_acq-HCP_T1w sub-NDARUC715YN4_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARUJ894ZXG_acq-HCP_T1w sub-NDARUJ894ZXG_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARVC305AC6_acq-HCP_T1w sub-NDARVC305AC6_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARWF422UK3_acq-HCP_T1w sub-NDARWF422UK3_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARWF593BNF_acq-HCP_T1w sub-NDARWF593BNF_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARWJ321WKG_acq-HCP_T1w sub-NDARWJ321WKG_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARXK303DDB_acq-HCP_T1w sub-NDARXK303DDB_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARXL023NG9_acq-HCP_T1w sub-NDARXL023NG9_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARZA694WHF_acq-HCP_T1w sub-NDARZA694WHF_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARZC499NVX_acq-HCP_T1w sub-NDARZC499NVX_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-RU_Derivatives_UZH/sub-NDARZJ603JM0_acq-HCP_T1w sub-NDARZJ603JM0_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARBA521RA8_T1w sub-NDARBA521RA8_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARDJ825GBP_T1w sub-NDARDJ825GBP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARFR109LKT_T1w sub-NDARFR109LKT_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARJM708VGE_T1w sub-NDARJM708VGE_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARKL327VRH_T1w sub-NDARKL327VRH_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARKR010EN7_T1w sub-NDARKR010EN7_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARKV482FU9_T1w sub-NDARKV482FU9_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARLA516PH1_T1w sub-NDARLA516PH1_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARNH342XLK_T1w sub-NDARNH342XLK_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARNU249EDF_T1w sub-NDARNU249EDF_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARPZ621ZLE_T1w sub-NDARPZ621ZLE_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARTU768MY1_T1w sub-NDARTU768MY1_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARYL272HDW_T1w sub-NDARYL272HDW_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARYU290HJ3_T1w sub-NDARYU290HJ3_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARDA695XTL_T1w sub-NDARDA695XTL_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARDR658DRA_T1w sub-NDARDR658DRA_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDAREK544ENR_T1w sub-NDAREK544ENR_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDAREY962BM7_T1w sub-NDAREY962BM7_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARFZ296UNG_T1w sub-NDARFZ296UNG_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARGY148EVU_T1w sub-NDARGY148EVU_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARHP558MGA_T1w sub-NDARHP558MGA_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARJH925ZCD_T1w sub-NDARJH925ZCD_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARKA429EPF_T1w sub-NDARKA429EPF_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARKX761BH9_T1w sub-NDARKX761BH9_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARPG072ZZ7_T1w sub-NDARPG072ZZ7_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARTY625VHZ_T1w sub-NDARTY625VHZ_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARUY876VL1_T1w sub-NDARUY876VL1_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARVG148WHV_T1w sub-NDARVG148WHV_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARVH070WH6_T1w sub-NDARVH070WH6_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARWC737UJ0_T1w sub-NDARWC737UJ0_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-SI_Derivatives_UZH/sub-NDARWX033HYK_T1w sub-NDARWX033HYK_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARCU891YET_acq-VNav_T1w sub-NDARCU891YET_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARDD854GF8_acq-VNav_T1w sub-NDARDD854GF8_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARGH592NZ2_acq-VNav_T1w sub-NDARGH592NZ2_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARJJ343TR0_acq-VNav_T1w sub-NDARJJ343TR0_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARLF446MT5_acq-VNav_T1w sub-NDARLF446MT5_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARLM196YRG_acq-VNav_T1w sub-NDARLM196YRG_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARLP507NKW_acq-VNav_T1w sub-NDARLP507NKW_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARLY114PDC_acq-VNav_T1w sub-NDARLY114PDC_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARMZ518UH1_acq-VNav_T1w sub-NDARMZ518UH1_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARNK489GNR_acq-VNav_T1w sub-NDARNK489GNR_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARPH022TRY_acq-VNav_T1w sub-NDARPH022TRY_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARPX661BF1_acq-VNav_T1w sub-NDARPX661BF1_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARRW481GFE_acq-VNav_T1w sub-NDARRW481GFE_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARUF152ARR_acq-VNav_T1w sub-NDARUF152ARR_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARVV473XTY_acq-VNav_T1w sub-NDARVV473XTY_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARXE912NZP_acq-VNav_T1w sub-NDARXE912NZP_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARXF294ME0_acq-VNav_T1w sub-NDARXF294ME0_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARXZ902NFM_acq-VNav_T1w sub-NDARXZ902NFM_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARYK164AEJ_acq-VNav_T1w sub-NDARYK164AEJ_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARYW789GNP_acq-VNav_T1w sub-NDARYW789GNP_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARZC058BA5_acq-VNav_T1w sub-NDARZC058BA5_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARZJ539CD9_acq-VNav_T1w sub-NDARZJ539CD9_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARBW268XPY_acq-HCP_T1w sub-NDARBW268XPY_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARZV421TCZ_acq-HCP_run-01_T1w sub-NDARZV421TCZ_acq-HCP_run-01_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARAA947ZG5_acq-VNav_T1w sub-NDARAA947ZG5_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARAD615WLJ_acq-VNav_T1w sub-NDARAD615WLJ_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARAT680GJA_acq-VNav_T1w sub-NDARAT680GJA_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARAV519RND_acq-VNav_T1w sub-NDARAV519RND_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARBL214YLX_acq-VNav_T1w sub-NDARBL214YLX_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARBN365EV3_acq-VNav_T1w sub-NDARBN365EV3_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARCD687JUZ_acq-VNav_T1w sub-NDARCD687JUZ_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARCN500KJG_acq-VNav_T1w sub-NDARCN500KJG_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARDB161LU6_acq-VNav_T1w sub-NDARDB161LU6_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARDE877RFH_acq-VNav_T1w sub-NDARDE877RFH_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARDF374LGN_acq-VNav_T1w sub-NDARDF374LGN_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDAREM155HGQ_acq-VNav_T1w sub-NDAREM155HGQ_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARFB322DRA_acq-VNav_T1w sub-NDARFB322DRA_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARFR696PLG_acq-VNav_T1w sub-NDARFR696PLG_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARFT787HJW_acq-VNav_T1w sub-NDARFT787HJW_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARFU916UZY_acq-VNav_T1w sub-NDARFU916UZY_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARGE994BMX_acq-VNav_T1w sub-NDARGE994BMX_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARGZ059UVR_acq-VNav_T1w sub-NDARGZ059UVR_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARHG594GKH_acq-VNav_T1w sub-NDARHG594GKH_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARHH819LH3_acq-VNav_T1w sub-NDARHH819LH3_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARHW933UVJ_acq-VNav_T1w sub-NDARHW933UVJ_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARJJ277JP3_acq-VNav_T1w sub-NDARJJ277JP3_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARJT172UE0_acq-VNav_T1w sub-NDARJT172UE0_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARJY747PRJ_acq-VNav_T1w sub-NDARJY747PRJ_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARKU649DB7_acq-VNav_T1w sub-NDARKU649DB7_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARKX528PH3_acq-VNav_T1w sub-NDARKX528PH3_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARKZ085UKQ_acq-VNav_T1w sub-NDARKZ085UKQ_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARLJ355VAG_acq-VNav_T1w sub-NDARLJ355VAG_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARLR924YAV_acq-VNav_T1w sub-NDARLR924YAV_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARNA421FL7_acq-VNav_T1w sub-NDARNA421FL7_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARNW528VXP_acq-VNav_T1w sub-NDARNW528VXP_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARPH152GU1_acq-VNav_T1w sub-NDARPH152GU1_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARPH176EWC_acq-VNav_T1w sub-NDARPH176EWC_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARPH542LMH_acq-VNav_T1w sub-NDARPH542LMH_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARPR537HF5_acq-VNav_T1w sub-NDARPR537HF5_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARPT670LAY_acq-VNav_T1w sub-NDARPT670LAY_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARRC982ZE9_acq-VNav_T1w sub-NDARRC982ZE9_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARRL379BET_acq-VNav_T1w sub-NDARRL379BET_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARRY768ZH3_acq-VNav_T1w sub-NDARRY768ZH3_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARTC227AXA_acq-VNav_T1w sub-NDARTC227AXA_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARTR464DCR_acq-VNav_T1w sub-NDARTR464DCR_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARUC771VM5_acq-VNav_T1w sub-NDARUC771VM5_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARVC673HFA_acq-VNav_T1w sub-NDARVC673HFA_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARVG777EUZ_acq-VNav_T1w sub-NDARVG777EUZ_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARVM774PA5_acq-VNav_T1w sub-NDARVM774PA5_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARWP817CVB_acq-VNav_T1w sub-NDARWP817CVB_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARWV625CRP_acq-VNav_T1w sub-NDARWV625CRP_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARXB250PAC_acq-VNav_T1w sub-NDARXB250PAC_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARXK009VGV_acq-VNav_T1w sub-NDARXK009VGV_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARXV094ZHH_acq-VNav_T1w sub-NDARXV094ZHH_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARZZ810LVF_acq-VNav_T1w sub-NDARZZ810LVF_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARAM197GFY_acq-HCP_T1w sub-NDARAM197GFY_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDAREY897LB1_acq-HCP_T1w sub-NDAREY897LB1_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARGR125APK_acq-HCP_T1w sub-NDARGR125APK_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARGY959RN8_acq-HCP_T1w sub-NDARGY959RN8_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARJK842BCN_acq-HCP_T1w sub-NDARJK842BCN_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARTR175UDC_acq-HCP_run-01_T1w sub-NDARTR175UDC_acq-HCP_run-01_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARUF230BYM_acq-HCP_T1w sub-NDARUF230BYM_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARWT694TXM_acq-HCP_T1w sub-NDARWT694TXM_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARYD958HAX_acq-HCP_T1w sub-NDARYD958HAX_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARYH603BDN_acq-HCP_T1w sub-NDARYH603BDN_acq-HCP_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CBIC_Derivatives_UZH/sub-NDARZH521MMD_acq-HCP_run-01_T1w sub-NDARZH521MMD_acq-HCP_run-01_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CUNY_Derivatives_UZH/sub-NDARCD182XT1_acq-VNav_T1w sub-NDARCD182XT1_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CUNY_Derivatives_UZH/sub-NDARCA146GG1_acq-VNav_T1w sub-NDARCA146GG1_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CUNY_Derivatives_UZH/sub-NDARMA273ZL6_acq-VNav_T1w sub-NDARMA273ZL6_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CUNY_Derivatives_UZH/sub-NDARND085WZK_acq-VNav_T1w sub-NDARND085WZK_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CUNY_Derivatives_UZH/sub-NDARPL440BX5_acq-VNav_T1w sub-NDARPL440BX5_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CUNY_Derivatives_UZH/sub-NDARUY024RVP_acq-VNav_T1w sub-NDARUY024RVP_acq-VNav_T1w
ln -s /mnt/methlab-drive/methlab_data/HBN/MRI/Site-CUNY_Derivatives_UZH/sub-NDARYX853TAX_acq-VNav_T1w sub-NDARYX853TAX_acq-VNav_T1w
